### ISSUE TITLE
docker user/group not using uid/gid

### ISSUE THREAD

**Issue by hotzen** [lludlow/autogen-studio#47]
Hello, I have problems to boot the container, failing with
`PermissionError: [Errno 13] Permission denied: '/app/.autogenstudio/files/'`

Checking the [Dockerfile](https://github.com/lludlow/autogen-studio/blob/master/Dockerfile#L8), the respective /app dir is created for user/group autogen without a uid/gid assigned.

What is the recommended docker-compose/host setup for this directory to avoid the permission problems?

**Comment by lludlow** [comment]
make sure whatever path you are mapping /app/.autogenstudio to  is writable by the user docker is running as. I have yet to run into a permissions issue
