### ISSUE TITLE
[Question] - DockerFile

### ISSUE THREAD

**Issue by fahadshery** [lludlow/autogen-studio#50]
Hi,

Thanks for making this. I was wondering if there was a particular reason for creating a python `venv` in the image?
autogenstudio provides the following `DockerFile`:

```
FROM python:3.10

WORKDIR /code

RUN pip install -U gunicorn autogenstudio

RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH \
    AUTOGENSTUDIO_APPDIR=/home/user/app

WORKDIR $HOME/app

COPY --chown=user . $HOME/app

CMD gunicorn -w $((2 * $(getconf _NPROCESSORS_ONLN) + 1)) --timeout 12600 -k uvicorn.workers.UvicornWorker autogenstudio.web.app:app --bind "0.0.0.0:8081"
```

**Comment by lludlow** [comment]
No, now that you pointed it out. I think it was more out of habit. I'll update it next time I pull in updates

**Comment by fahadshery** [comment]
thanks, what about using `gunicorn`? 
I haven't tested the performance gains tbh but because it was officially recommended by `autogen` team...I think it's worth looking into!

**Comment by lludlow** [comment]
this container is for autogenstudion packaged with autogen, changing the UI is out of scope
